In [2]:
import numpy as np
print(np.__version__)

1.18.1


# Questions 1:
Create a numpy array starting from 2 till 50 with a stepsize of 3.

In [5]:
np.arange(2,51,3)

array([ 2,  5,  8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50])

# Questions 2:
Accept two lists of 5 elements each from the user.
Convert them to numpy arrays. Concatenate these arrays and print it. Also sort these arrays and print it.

In [27]:
lst1 = []
lst2 = []


for i in range(0,6):
    user_input = int(input())
    lst1.append(user_input)
np_lst1 = np.array(lst1)
print('Numpy array of List 1..........',np_lst1)

for i in range(0,6):
    user_input =int(input())
    lst2.append(user_input)
np_lst2 = np.array(lst2)
print('Numpy array of List 2..........',np_lst2)
print('------------------------')

np_concat = np.concatenate((np_lst1,np_lst2), axis = None)
np_sort = np.sort(np_concat)

print('Concatenated arrays.............',np_concat)
print('------------------------')
print('sorted arrays...................',np_sort)

96
56
23
45
85
36
Numpy array of List 1.......... [96 56 23 45 85 36]
22
05
65
93
110
633
Numpy array of List 2.......... [ 22   5  65  93 110 633]
------------------------
Concatenated arrays............. [ 96  56  23  45  85  36  22   5  65  93 110 633]
------------------------
sorted arrays................... [  5  22  23  36  45  56  65  85  93  96 110 633]


# Questions 3:
Write a code snippet to find the dimensions of a ndarray and its size.

In [44]:
arr = np.arange(0,10)
print('Array.........',arr)
print('Dimensions....',arr.ndim)
print('Size..........',arr.size)

Array......... [0 1 2 3 4 5 6 7 8 9]
Dimensions.... 1
Size.......... 10


In [49]:
arr = np.arange(0,10).reshape(5,2)
print(arr)
print('\nDimensions....',arr.ndim) 
print('Size..........',arr.size)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Dimensions.... 2
Size.......... 10


In [52]:
arr = np.arange(0,20).reshape(2,2,5)
print(arr)
print('\nDimensions....',arr.ndim) 
print('Size..........',arr.size)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]

Dimensions.... 3
Size.......... 20


In [54]:
arr = np.arange(0,40).reshape(2,2,5,2)
print(arr)
print('\nDimensions....',arr.ndim) 
print('Size..........',arr.size)

[[[[ 0  1]
   [ 2  3]
   [ 4  5]
   [ 6  7]
   [ 8  9]]

  [[10 11]
   [12 13]
   [14 15]
   [16 17]
   [18 19]]]


 [[[20 21]
   [22 23]
   [24 25]
   [26 27]
   [28 29]]

  [[30 31]
   [32 33]
   [34 35]
   [36 37]
   [38 39]]]]

Dimensions.... 4
Size.......... 40


# Questions 4:
How to convert a 1D array into a 2D array? Demonstrate with the help of a code snippet
Hint: np.newaxis, np.expand_dims

In [76]:
arr1d = np.array([1,2,3,4,5,6,7,8,9])
print('1D Array :')
print(arr1d)

arr2d = np.expand_dims(arr1d, axis=0)
print('\n 2D Array :')
print(arr2d)


1D Array :
[1 2 3 4 5 6 7 8 9]

 2D Array :
[[1 2 3 4 5 6 7 8 9]]


# Questions 5:
Consider two square numpy arrays. Stack them vertically and horizontally.
Hint: Use vstack(), hstack()

In [87]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

vertical_arr = np.vstack((arr1,arr2))
horizontal_arr = np.hstack((arr1,arr2))

print('vertically Stack :')
print(vertical_arr)

print('\n horizontally Stack :')
print(horizontal_arr)

vertically Stack :
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

 horizontally Stack :
[[1 2 5 6]
 [3 4 7 8]]


# Questions 6:
How to get unique items and counts of unique items?

In [91]:
input_list = [1,2,3,4,4,5,6,7,8,8,8] 

l1 = [] 

count = 0

for item in input_list: 
    if item not in l1: 
        count += 1
        l1.append(item) 


print("No of unique items are:", count) 

No of unique items are: 8
